// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinSmtpRelay.Storage;

#nullable disable

namespace WinSmtpRelay.Storage.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    [Migration("20260308154458_AddDailyStatistics")]
    partial class AddDailyStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WinSmtpRelay.Core.Models.DailyStatistics", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageDeliveryTimeMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBounced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("DailyStatistics");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.DeliveryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueuedMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteServer")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueuedMessageId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("DeliveryLogs");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.QueuedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthenticatedUser")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawMessage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("NextRetryUtc");

                    b.HasIndex("Status");

                    b.ToTable("QueuedMessages");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.RelayUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedSenderAddresses")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RateLimitPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("RelayUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
