// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinSmtpRelay.Storage;

#nullable disable

namespace WinSmtpRelay.Storage.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    [Migration("20260309121533_AddConfigurationEntities")]
    partial class AddConfigurationEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WinSmtpRelay.Core.Models.AcceptedDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("AcceptedDomains");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.DailyStatistics", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageDeliveryTimeMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBounced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("DailyStatistics");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.DeliveryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueuedMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteServer")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueuedMessageId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("DeliveryLogs");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.DkimDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("DkimDomains");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.DomainRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainPattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SendConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SendConnectorId");

                    b.HasIndex("SortOrder");

                    b.ToTable("DomainRoutes");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.HeaderRewriteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("HeaderRewriteEntries");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.IpAccessRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("IpAccessRules");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.QueuedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthenticatedUser")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawMessage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("NextRetryUtc");

                    b.HasIndex("Status");

                    b.ToTable("QueuedMessages");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.RateLimitSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAuthBanMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAuthBanThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConnectionsPerIpPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMessagesPerSenderPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMessagesPerSenderPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RateLimitSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FailedAuthBanMinutes = 30,
                            FailedAuthBanThreshold = 5,
                            MaxConnectionsPerIpPerMinute = 30,
                            MaxMessagesPerSenderPerDay = 1000,
                            MaxMessagesPerSenderPerMinute = 20,
                            UpdatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.ReceiveConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImplicitTls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMessageSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireTls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReceiveConnectors");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.RelayUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedSenderAddresses")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RateLimitPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("RelayUsers");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.SendConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentDeliveries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetryHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OpportunisticTls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetryIntervalsMinutes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmartHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmartHostPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SendConnectors");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.SenderRewriteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromPattern")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("SenderRewriteEntries");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.DomainRoute", b =>
                {
                    b.HasOne("WinSmtpRelay.Core.Models.SendConnector", "SendConnector")
                        .WithMany("DomainRoutes")
                        .HasForeignKey("SendConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SendConnector");
                });

            modelBuilder.Entity("WinSmtpRelay.Core.Models.SendConnector", b =>
                {
                    b.Navigation("DomainRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
